//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ethosIQ_NGCC_Shared.WFMRealTime {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFMRealTime.IWFMRealTime")]
    public interface IWFMRealTime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFMRealTime/SendFullAgentState", ReplyAction="http://tempuri.org/IWFMRealTime/SendFullAgentStateResponse")]
        void SendFullAgentState(string FullRTAString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFMRealTime/SendFullAgentState", ReplyAction="http://tempuri.org/IWFMRealTime/SendFullAgentStateResponse")]
        System.Threading.Tasks.Task SendFullAgentStateAsync(string FullRTAString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFMRealTime/SendAgentState", ReplyAction="http://tempuri.org/IWFMRealTime/SendAgentStateResponse")]
        void SendAgentState(string AgentID, string StateCode, System.DateTime StateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWFMRealTime/SendAgentState", ReplyAction="http://tempuri.org/IWFMRealTime/SendAgentStateResponse")]
        System.Threading.Tasks.Task SendAgentStateAsync(string AgentID, string StateCode, System.DateTime StateTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWFMRealTimeChannel : ethosIQ_NGCC_Shared.WFMRealTime.IWFMRealTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WFMRealTimeClient : System.ServiceModel.ClientBase<ethosIQ_NGCC_Shared.WFMRealTime.IWFMRealTime>, ethosIQ_NGCC_Shared.WFMRealTime.IWFMRealTime {
        
        public WFMRealTimeClient() {
        }
        
        public WFMRealTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WFMRealTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFMRealTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WFMRealTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendFullAgentState(string FullRTAString) {
            base.Channel.SendFullAgentState(FullRTAString);
        }
        
        public System.Threading.Tasks.Task SendFullAgentStateAsync(string FullRTAString) {
            return base.Channel.SendFullAgentStateAsync(FullRTAString);
        }
        
        public void SendAgentState(string AgentID, string StateCode, System.DateTime StateTime) {
            base.Channel.SendAgentState(AgentID, StateCode, StateTime);
        }
        
        public System.Threading.Tasks.Task SendAgentStateAsync(string AgentID, string StateCode, System.DateTime StateTime) {
            return base.Channel.SendAgentStateAsync(AgentID, StateCode, StateTime);
        }
    }
}
